### PR TITLE
added styling

### PR DESCRIPTION
**Pull request by verissimohenry**

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required ♻🛑**

<hr>

Hello there, great job you've done so far on this project. It almost looks like the original page. However, there are still a few more improvements to make in order to get this project completed 😊🙏

<hr>

- [ ] Please write a descriptive Pull Request (PR) summary for your project (Refresh your memory by following instructions of this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- [ ] Please write a descriptive and well-structured README file for your project (Also give yourself a quick reminder from this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- [ ] Kindly make sure to make any clickable element within your page inside of an anchor tag ```<a href="#">``` i.e. The Hamburger button, the search icon, and the images (as they're commonly referring to other links)
- [ ] "**The Theory of Inflation**" part is not styled properly, please adjust that.
- [ ] I see you've missed the following parts of the page:- 1) The right-sided section which you were supposed to use the ```<aside>``` tag for creating it. 2) The before last section (the grid). Kindly implement those three sections and style them correctly using all of the three techniques (Flex, Float, and Grid) as described in the project specifications.
- [ ] Kindly follow the Git Flow Guidelines and correct your linter errors in order for your PR to pass the Github checks.
- [ ] Please follow the DRY rule (Don't Repeat Yourself) It's a very important and common rule that being followed by all programmers i.e.
```
    .identity {
      width: 90%;
    }
  
    .article-body {
      width: 90%;
    }
```

Could be ...
```
    .identity,
    .article-body {
      width: 90%;
    }
```
And measure all of your code the same way 😊🙏

<hr>

Kindly do the above changes and ask for another review.
Good luck and happy coding 👨‍💻💻

**Comment by verissimohenry** [comment]
Thanks you..

I will make the corrections immediately.

**Comment by verissimohenry** [comment]
Hi

I asked for a code review 2hrs ago but I've not gotten it please.

Thank you.

**Comment by verissimohenry** [comment]
hi.
Because of this, I think I have missed the deadline, don't know if I can submit it again.

please help

**Pull request merged**
